<?php

/*
 * This file is part of the Utilities package.
 *
 * (c) Mark Fluehmann mark.fluehmann@gmail.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/*
 * International Components for Unicode (ICU ) Data
 * Source: https://www.localeplanet.com/icu/currency.html
 *
 * code                 currency code
 * display              display name
 * symbol               currency symbol
 * digits               default fraction units
 * iso               	ISO 4217 Code
 */

return [

	['code' => 'ADP', 'display' => 'Andorran Peseta', 'symbol' => 'ADP', 'digits' => 0, 'iso' => 20],
	['code' => 'AED', 'display' => 'United Arab Emirates Dirham', 'symbol' => 'AED', 'digits' => 2, 'iso' => 784 ],
	['code' => 'AFA', 'display' => 'Afghan Afghani (1927–2002)', 'symbol' => 'AFA', 'digits' => 2, 'iso' => 4 ],
	['code' => 'AFN', 'display' => 'Afghan Afghani', 'symbol' => 'AFN', 'digits' => 0, 'iso' => 971 ],
	['code' => 'ALK', 'display' => 'Albanian Lek (1946–1965)', 'symbol' => 'ALK', 'digits' => 2, 'iso' => 8 ],
	['code' => 'ALL', 'display' => 'Albanian Lek', 'symbol' => 'ALL', 'digits' => 0, 'iso' => 8 ],
	['code' => 'AMD', 'display' => 'Armenian Dram', 'symbol' => 'AMD', 'digits' => 0, 'iso' => 51 ],
	['code' => 'ANG', 'display' => 'Netherlands Antillean Guilder', 'symbol' => 'ANG', 'digits' => 2, 'iso' => 532 ],
	['code' => 'AOA', 'display' => 'Angolan Kwanza', 'symbol' => 'AOA', 'digits' => 2, 'iso' => 973 ],
	['code' => 'AOK', 'display' => 'Angolan Kwanza (1977–1991)', 'symbol' => 'AOK', 'digits' => 2, 'iso' => 24 ],
	['code' => 'AON', 'display' => 'Angolan New Kwanza (1990–2000)', 'symbol' => 'AON', 'digits' => 2, 'iso' => 24 ],
	['code' => 'AOR', 'display' => 'Angolan Readjusted Kwanza (1995–1999)', 'symbol' => 'AOR', 'digits' => 2, 'iso' => 982 ],
	['code' => 'ARA', 'display' => 'Argentine Austral', 'symbol' => 'ARA', 'digits' => 2, 'iso' => 32 ],
	['code' => 'ARL', 'display' => 'Argentine Peso Ley (1970–1983)', 'symbol' => 'ARL', 'digits' => 2, 'iso' => 0 ],
	['code' => 'ARM', 'display' => 'Argentine Peso (1881–1970)', 'symbol' => 'ARM', 'digits' => 2, 'iso' => 0 ],
	['code' => 'ARP', 'display' => 'Argentine Peso (1983–1985)', 'symbol' => 'ARP', 'digits' => 2, 'iso' => 32 ],
	['code' => 'ARS', 'display' => 'Argentine Peso', 'symbol' => 'ARS', 'digits' => 2, 'iso' => 32 ],
	['code' => 'ATS', 'display' => 'Austrian Schilling', 'symbol' => 'öS', 'digits' => 2, 'iso' => 40 ],
	['code' => 'AUD', 'display' => 'Australian Dollar', 'symbol' => 'AU$', 'digits' => 2, 'iso' => 36 ],
	['code' => 'AWG', 'display' => 'Aruban Florin', 'symbol' => 'AWG', 'digits' => 2, 'iso' => 533 ],
	['code' => 'AZM', 'display' => 'Azerbaijani Manat (1993–2006)', 'symbol' => 'AZM', 'digits' => 2, 'iso' => 31 ],
	['code' => 'AZN', 'display' => 'Azerbaijani Manat', 'symbol' => 'AZN', 'digits' => 2, 'iso' => 944 ],
	['code' => 'BAD', 'display' => 'Bosnia-Herzegovina Dinar (1992–1994)', 'symbol' => 'BAD', 'digits' => 2, 'iso' => 70 ],
	['code' => 'BAM', 'display' => 'Bosnia-Herzegovina Convertible Mark', 'symbol' => 'BAM', 'digits' => 2, 'iso' => 977 ],
	['code' => 'BAN', 'display' => 'Bosnia-Herzegovina New Dinar (1994–1997)', 'symbol' => 'BAN', 'digits' => 2, 'iso' => 0 ],
	['code' => 'BBD', 'display' => 'Barbadian Dollar', 'symbol' => 'BBD', 'digits' => 2, 'iso' => 52 ],
	['code' => 'BDT', 'display' => 'Bangladeshi Taka', 'symbol' => 'BDT', 'digits' => 2, 'iso' => 50 ],
	['code' => 'BEC', 'display' => 'Belgian Franc (convertible)', 'symbol' => 'BEC', 'digits' => 2, 'iso' => 993 ],
	['code' => 'BEF', 'display' => 'Belgian Franc', 'symbol' => 'BEF', 'digits' => 2, 'iso' => 56 ],
	['code' => 'BEL', 'display' => 'Belgian Franc (financial)', 'symbol' => 'BEL', 'digits' => 2, 'iso' => 992 ],
	['code' => 'BGL', 'display' => 'Bulgarian Hard Lev', 'symbol' => 'BGL', 'digits' => 2, 'iso' => 100 ],
	['code' => 'BGM', 'display' => 'Bulgarian Socialist Lev', 'symbol' => 'BGK', 'digits' => 2, 'iso' => 0 ],
	['code' => 'BGN', 'display' => 'Bulgarian Lev', 'symbol' => 'BGN', 'digits' => 2, 'iso' => 975 ],
	['code' => 'BGO', 'display' => 'Bulgarian Lev (1879–1952)', 'symbol' => 'BGJ', 'digits' => 2, 'iso' => 0 ],
	['code' => 'BHD', 'display' => 'Bahraini Dinar', 'symbol' => 'BHD', 'digits' => 3, 'iso' => 48 ],
	['code' => 'BIF', 'display' => 'Burundian Franc', 'symbol' => 'BIF', 'digits' => 0, 'iso' => 108 ],
	['code' => 'BMD', 'display' => 'Bermudan Dollar', 'symbol' => 'BMD', 'digits' => 2, 'iso' => 60 ],
	['code' => 'BND', 'display' => 'Brunei Dollar', 'symbol' => 'BND', 'digits' => 2, 'iso' => 96 ],
	['code' => 'BOB', 'display' => 'Bolivian Boliviano', 'symbol' => 'BOB', 'digits' => 2, 'iso' => 68 ],
	['code' => 'BOL', 'display' => 'Bolivian Boliviano (1863–1963)', 'symbol' => 'BOL', 'digits' => 2, 'iso' => 0 ],
	['code' => 'BOP', 'display' => 'Bolivian Peso', 'symbol' => 'BOP', 'digits' => 2, 'iso' => 68 ],
	['code' => 'BOV', 'display' => 'Bolivian Mvdol', 'symbol' => 'BOV', 'digits' => 2, 'iso' => 984 ],
	['code' => 'BRB', 'display' => 'Brazilian New Cruzeiro (1967–1986)', 'symbol' => 'BRB', 'digits' => 2, 'iso' => 76 ],
	['code' => 'BRC', 'display' => 'Brazilian Cruzado (1986–1989)', 'symbol' => 'BRC', 'digits' => 2, 'iso' => 76 ],
	['code' => 'BRE', 'display' => 'Brazilian Cruzeiro (1990–1993)', 'symbol' => 'BRE', 'digits' => 2, 'iso' => 76 ],
	['code' => 'BRL', 'display' => 'Brazilian Real', 'symbol' => 'R$', 'digits' => 2, 'iso' => 986 ],
	['code' => 'BRN', 'display' => 'Brazilian New Cruzado (1989–1990)', 'symbol' => 'BRN', 'digits' => 2, 'iso' => 76 ],
	['code' => 'BRR', 'display' => 'Brazilian Cruzeiro (1993–1994)', 'symbol' => 'BRR', 'digits' => 2, 'iso' => 987 ],
	['code' => 'BRZ', 'display' => 'Brazilian Cruzeiro (1942–1967)', 'symbol' => 'BRZ', 'digits' => 2, 'iso' => 0 ],
	['code' => 'BSD', 'display' => 'Bahamian Dollar', 'symbol' => 'BSD', 'digits' => 2, 'iso' => 44 ],
	['code' => 'BTN', 'display' => 'Bhutanese Ngultrum', 'symbol' => 'BTN', 'digits' => 2, 'iso' => 64 ],
	['code' => 'BUK', 'display' => 'Burmese Kyat', 'symbol' => 'BUK', 'digits' => 2, 'iso' => 104 ],
	['code' => 'BWP', 'display' => 'Botswanan Pula', 'symbol' => 'BWP', 'digits' => 2, 'iso' => 72 ],
	['code' => 'BYB', 'display' => 'Belarusian Ruble (1994–1999)', 'symbol' => 'BYB', 'digits' => 2, 'iso' => 112 ],
	['code' => 'BYN', 'display' => 'Belarusian Ruble', 'symbol' => 'BYN', 'digits' => 2, 'iso' => 933 ],
	['code' => 'BYR', 'display' => 'Belarusian Ruble (2000–2016)', 'symbol' => 'BYR', 'digits' => 0, 'iso' => 974 ],
	['code' => 'BZD', 'display' => 'Belize Dollar', 'symbol' => 'BZD', 'digits' => 2, 'iso' => 84 ],
	['code' => 'CAD', 'display' => 'Canadian Dollar', 'symbol' => 'CA$', 'digits' => 2, 'iso' => 124 ],
	['code' => 'CDF', 'display' => 'Congolese Franc', 'symbol' => 'CDF', 'digits' => 2, 'iso' => 976 ],
	['code' => 'CHE', 'display' => 'WIR Euro', 'symbol' => 'CHE', 'digits' => 2, 'iso' => 947 ],
	['code' => 'CHF', 'display' => 'Swiss Franc', 'symbol' => 'CHF', 'digits' => 2, 'iso' => 756 ],
	['code' => 'CHW', 'display' => 'WIR Franc', 'symbol' => 'CHW', 'digits' => 2, 'iso' => 948 ],
	['code' => 'CLE', 'display' => 'Chilean Escudo', 'symbol' => 'CLE', 'digits' => 2, 'iso' => 0 ],
	['code' => 'CLF', 'display' => 'Chilean Unit of Account (UF)', 'symbol' => 'CLF', 'digits' => 4, 'iso' => 990 ],
	['code' => 'CLP', 'display' => 'Chilean Peso', 'symbol' => 'CLP', 'digits' => 0, 'iso' => 152 ],
	['code' => 'CNH', 'display' => 'Chinese Yuan (offshore)', 'symbol' => 'CNH', 'digits' => 2, 'iso' => 0 ],
	['code' => 'CNX', 'display' => 'Chinese People’s Bank Dollar', 'symbol' => 'CNX', 'digits' => 2, 'iso' => 0 ],
	['code' => 'CNY', 'display' => 'Chinese Yuan', 'symbol' => 'CN¥', 'digits' => 2, 'iso' => 156 ],
	['code' => 'COP', 'display' => 'Colombian Peso', 'symbol' => 'COP', 'digits' => 0, 'iso' => 170 ],
	['code' => 'COU', 'display' => 'Colombian Real Value Unit', 'symbol' => 'COU', 'digits' => 2, 'iso' => 970 ],
	['code' => 'CRC', 'display' => 'Costa Rican Colón', 'symbol' => 'CRC', 'digits' => 2, 'iso' => 188 ],
	['code' => 'CSD', 'display' => 'Serbian Dinar (2002–2006)', 'symbol' => 'CSD', 'digits' => 2, 'iso' => 891 ],
	['code' => 'CSK', 'display' => 'Czechoslovak Hard Koruna', 'symbol' => 'CSK', 'digits' => 2, 'iso' => 200 ],
	['code' => 'CUC', 'display' => 'Cuban Convertible Peso', 'symbol' => 'CUC', 'digits' => 2, 'iso' => 931 ],
	['code' => 'CUP', 'display' => 'Cuban Peso', 'symbol' => 'CUP', 'digits' => 2, 'iso' => 192 ],
	['code' => 'CVE', 'display' => 'Cape Verdean Escudo', 'symbol' => 'CVE', 'digits' => 2, 'iso' => 132 ],
	['code' => 'CYP', 'display' => 'Cypriot Pound', 'symbol' => 'CYP', 'digits' => 2, 'iso' => 196 ],
	['code' => 'CZK', 'display' => 'Czech Koruna', 'symbol' => 'CZK', 'digits' => 2, 'iso' => 203 ],
	['code' => 'DDM', 'display' => 'East German Mark', 'symbol' => 'DDM', 'digits' => 2, 'iso' => 278 ],
	['code' => 'DEM', 'display' => 'German Mark', 'symbol' => 'DM', 'digits' => 2, 'iso' => 276 ],
	['code' => 'DJF', 'display' => 'Djiboutian Franc', 'symbol' => 'DJF', 'digits' => 0, 'iso' => 262 ],
	['code' => 'DKK', 'display' => 'Danish Krone', 'symbol' => 'DKK', 'digits' => 2, 'iso' => 208 ],
	['code' => 'DOP', 'display' => 'Dominican Peso', 'symbol' => 'DOP', 'digits' => 2, 'iso' => 214 ],
	['code' => 'DZD', 'display' => 'Algerian Dinar', 'symbol' => 'DZD', 'digits' => 2, 'iso' => 12 ],
	['code' => 'ECS', 'display' => 'Ecuadorian Sucre', 'symbol' => 'ECS', 'digits' => 2, 'iso' => 218 ],
	['code' => 'ECV', 'display' => 'Ecuadorian Unit of Constant Value', 'symbol' => 'ECV', 'digits' => 2, 'iso' => 983 ],
	['code' => 'EEK', 'display' => 'Estonian Kroon', 'symbol' => 'EEK', 'digits' => 2, 'iso' => 233 ],
	['code' => 'EGP', 'display' => 'Egyptian Pound', 'symbol' => 'EGP', 'digits' => 2, 'iso' => 818 ],
	['code' => 'ERN', 'display' => 'Eritrean Nakfa', 'symbol' => 'ERN', 'digits' => 2, 'iso' => 232 ],
	['code' => 'ESA', 'display' => 'Spanish Peseta (A account)', 'symbol' => 'ESA', 'digits' => 2, 'iso' => 996 ],
	['code' => 'ESB', 'display' => 'Spanish Peseta (convertible account)', 'symbol' => 'ESB', 'digits' => 2, 'iso' => 995 ],
	['code' => 'ESP', 'display' => 'Spanish Peseta', 'symbol' => 'ESP', 'digits' => 0, 'iso' => 724 ],
	['code' => 'ETB', 'display' => 'Ethiopian Birr', 'symbol' => 'ETB', 'digits' => 2, 'iso' => 230 ],
	['code' => 'EUR', 'display' => 'Euro', 'symbol' => '€', 'digits' => 2, 'iso' => 978 ],
	['code' => 'FIM', 'display' => 'Finnish Markka', 'symbol' => 'FIM', 'digits' => 2, 'iso' => 246 ],
	['code' => 'FJD', 'display' => 'Fijian Dollar', 'symbol' => 'FJD', 'digits' => 2, 'iso' => 242 ],
	['code' => 'FKP', 'display' => 'Falkland Islands Pound', 'symbol' => 'FKP', 'digits' => 2, 'iso' => 238 ],
	['code' => 'FRF', 'display' => 'French Franc', 'symbol' => 'FRF', 'digits' => 2, 'iso' => 250 ],
	['code' => 'GBP', 'display' => 'British Pound', 'symbol' => '£', 'digits' => 2, 'iso' => 826 ],
	['code' => 'GEK', 'display' => 'Georgian Kupon Larit', 'symbol' => 'GEK', 'digits' => 2, 'iso' => 268 ],
	['code' => 'GEL', 'display' => 'Georgian Lari', 'symbol' => 'GEL', 'digits' => 2, 'iso' => 981 ],
	['code' => 'GHC', 'display' => 'Ghanaian Cedi (1979–2007)', 'symbol' => 'GHC', 'digits' => 2, 'iso' => 288 ],
	['code' => 'GHS', 'display' => 'Ghanaian Cedi', 'symbol' => 'GHS', 'digits' => 2, 'iso' => 936 ],
	['code' => 'GIP', 'display' => 'Gibraltar Pound', 'symbol' => 'GIP', 'digits' => 2, 'iso' => 292 ],
	['code' => 'GMD', 'display' => 'Gambian Dalasi', 'symbol' => 'GMD', 'digits' => 2, 'iso' => 270 ],
	['code' => 'GNF', 'display' => 'Guinean Franc', 'symbol' => 'GNF', 'digits' => 0, 'iso' => 324 ],
	['code' => 'GNS', 'display' => 'Guinean Syli', 'symbol' => 'GNS', 'digits' => 2, 'iso' => 324 ],
	['code' => 'GQE', 'display' => 'Equatorial Guinean Ekwele', 'symbol' => 'GQE', 'digits' => 2, 'iso' => 226 ],
	['code' => 'GRD', 'display' => 'Greek Drachma', 'symbol' => 'GRD', 'digits' => 2, 'iso' => 300 ],
	['code' => 'GTQ', 'display' => 'Guatemalan Quetzal', 'symbol' => 'GTQ', 'digits' => 2, 'iso' => 320 ],
	['code' => 'GWE', 'display' => 'Portuguese Guinea Escudo', 'symbol' => 'GWE', 'digits' => 2, 'iso' => 624 ],
	['code' => 'GWP', 'display' => 'Guinea-Bissau Peso', 'symbol' => 'GWP', 'digits' => 2, 'iso' => 624 ],
	['code' => 'GYD', 'display' => 'Guyanaese Dollar', 'symbol' => 'GYD', 'digits' => 0, 'iso' => 328 ],
	['code' => 'HKD', 'display' => 'Hong Kong Dollar', 'symbol' => 'HK$', 'digits' => 2, 'iso' => 344 ],
	['code' => 'HNL', 'display' => 'Honduran Lempira', 'symbol' => 'HNL', 'digits' => 2, 'iso' => 340 ],
	['code' => 'HRD', 'display' => 'Croatian Dinar', 'symbol' => 'HRD', 'digits' => 2, 'iso' => 191 ],
	['code' => 'HRK', 'display' => 'Croatian Kuna', 'symbol' => 'HRK', 'digits' => 2, 'iso' => 191 ],
	['code' => 'HTG', 'display' => 'Haitian Gourde', 'symbol' => 'HTG', 'digits' => 2, 'iso' => 332 ],
	['code' => 'HUF', 'display' => 'Hungarian Forint', 'symbol' => 'HUF', 'digits' => 2, 'iso' => 348 ],
	['code' => 'IDR', 'display' => 'Indonesian Rupiah', 'symbol' => 'IDR', 'digits' => 0, 'iso' => 360 ],
	['code' => 'IEP', 'display' => 'Irish Pound', 'symbol' => 'IEP', 'digits' => 2, 'iso' => 372 ],
	['code' => 'ILP', 'display' => 'Israeli Pound', 'symbol' => 'ILP', 'digits' => 2, 'iso' => 376 ],
	['code' => 'ILR', 'display' => 'Israeli Shekel (1980–1985)', 'symbol' => 'ILR', 'digits' => 2, 'iso' => 376 ],
	['code' => 'ILS', 'display' => 'Israeli New Shekel', 'symbol' => '₪', 'digits' => 2, 'iso' => 376 ],
	['code' => 'INR', 'display' => 'Indian Rupee', 'symbol' => '₹', 'digits' => 2, 'iso' => 356 ],
	['code' => 'IQD', 'display' => 'Iraqi Dinar', 'symbol' => 'IQD', 'digits' => 0, 'iso' => 368 ],
	['code' => 'IRR', 'display' => 'Iranian Rial', 'symbol' => 'IRR', 'digits' => 0, 'iso' => 364 ],
	['code' => 'ISJ', 'display' => 'Icelandic Króna (1918–1981)', 'symbol' => 'ISJ', 'digits' => 2, 'iso' => 352 ],
	['code' => 'ISK', 'display' => 'Icelandic Króna', 'symbol' => 'ISK', 'digits' => 0, 'iso' => 352 ],
	['code' => 'ITL', 'display' => 'Italian Lira', 'symbol' => 'ITL', 'digits' => 0, 'iso' => 380 ],
	['code' => 'JMD', 'display' => 'Jamaican Dollar', 'symbol' => 'JMD', 'digits' => 2, 'iso' => 388 ],
	['code' => 'JOD', 'display' => 'Jordanian Dinar', 'symbol' => 'JOD', 'digits' => 3, 'iso' => 400 ],
	['code' => 'JPY', 'display' => 'Japanese Yen', 'symbol' => '¥', 'digits' => 0, 'iso' => 392 ],
	['code' => 'KES', 'display' => 'Kenyan Shilling', 'symbol' => 'KES', 'digits' => 2, 'iso' => 404 ],
	['code' => 'KGS', 'display' => 'Kyrgystani Som', 'symbol' => 'KGS', 'digits' => 2, 'iso' => 417 ],
	['code' => 'KHR', 'display' => 'Cambodian Riel', 'symbol' => 'KHR', 'digits' => 2, 'iso' => 116 ],
	['code' => 'KMF', 'display' => 'Comorian Franc', 'symbol' => 'KMF', 'digits' => 0, 'iso' => 174 ],
	['code' => 'KPW', 'display' => 'North Korean Won', 'symbol' => 'KPW', 'digits' => 0, 'iso' => 408 ],
	['code' => 'KRH', 'display' => 'South Korean Hwan (1953–1962)', 'symbol' => 'KRH', 'digits' => 2, 'iso' => 0 ],
	['code' => 'KRO', 'display' => 'South Korean Won (1945–1953)', 'symbol' => 'KRO', 'digits' => 2, 'iso' => 0 ],
	['code' => 'KRW', 'display' => 'South Korean Won', 'symbol' => 'W', 'digits' => 0, 'iso' => 410 ],
	['code' => 'KWD', 'display' => 'Kuwaiti Dinar', 'symbol' => 'KWD', 'digits' => 3, 'iso' => 414 ],
	['code' => 'KYD', 'display' => 'Cayman Islands Dollar', 'symbol' => 'KYD', 'digits' => 2, 'iso' => 136 ],
	['code' => 'KZT', 'display' => 'Kazakhstani Tenge', 'symbol' => 'KZT', 'digits' => 2, 'iso' => 398 ],
	['code' => 'LAK', 'display' => 'Laotian Kip', 'symbol' => 'LAK', 'digits' => 0, 'iso' => 418 ],
	['code' => 'LBP', 'display' => 'Lebanese Pound', 'symbol' => 'LBP', 'digits' => 0, 'iso' => 422 ],
	['code' => 'LKR', 'display' => 'Sri Lankan Rupee', 'symbol' => 'LKR', 'digits' => 2, 'iso' => 144 ],
	['code' => 'LRD', 'display' => 'Liberian Dollar', 'symbol' => 'LRD', 'digits' => 2, 'iso' => 430 ],
	['code' => 'LSL', 'display' => 'Lesotho Loti', 'symbol' => 'LSL', 'digits' => 2, 'iso' => 426 ],
	['code' => 'LTL', 'display' => 'Lithuanian Litas', 'symbol' => 'LTL', 'digits' => 2, 'iso' => 440 ],
	['code' => 'LTT', 'display' => 'Lithuanian Talonas', 'symbol' => 'LTT', 'digits' => 2, 'iso' => 440 ],
	['code' => 'LUC', 'display' => 'Luxembourgian Convertible Franc', 'symbol' => 'LUC', 'digits' => 2, 'iso' => 989 ],
	['code' => 'LUF', 'display' => 'Luxembourgian Franc', 'symbol' => 'LUF', 'digits' => 0, 'iso' => 442 ],
	['code' => 'LUL', 'display' => 'Luxembourg Financial Franc', 'symbol' => 'LUL', 'digits' => 2, 'iso' => 988 ],
	['code' => 'LVL', 'display' => 'Latvian Lats', 'symbol' => 'LVL', 'digits' => 2, 'iso' => 428 ],
	['code' => 'LVR', 'display' => 'Latvian Ruble', 'symbol' => 'LVR', 'digits' => 2, 'iso' => 428 ],
	['code' => 'LYD', 'display' => 'Libyan Dinar', 'symbol' => 'LYD', 'digits' => 3, 'iso' => 434 ],
	['code' => 'MAD', 'display' => 'Moroccan Dirham', 'symbol' => 'MAD', 'digits' => 2, 'iso' => 504 ],
	['code' => 'MAF', 'display' => 'Moroccan Franc', 'symbol' => 'MAF', 'digits' => 2, 'iso' => 0 ],
	['code' => 'MCF', 'display' => 'Monegasque Franc', 'symbol' => 'MCF', 'digits' => 2, 'iso' => 0 ],
	['code' => 'MDC', 'display' => 'Moldovan Cupon', 'symbol' => 'MDC', 'digits' => 2, 'iso' => 0 ],
	['code' => 'MDL', 'display' => 'Moldovan Leu', 'symbol' => '2', 'digits' => 2, 'iso' => 498 ],
	['code' => 'MGA', 'display' => 'Malagasy Ariary', 'symbol' => 'MGA', 'digits' => 0, 'iso' => 969 ],
	['code' => 'MGF', 'display' => 'Malagasy Franc', 'symbol' => 'MGF', 'digits' => 0, 'iso' => 450 ],
	['code' => 'MKD', 'display' => 'Macedonian Denar', 'symbol' => 'MKD', 'digits' => 2, 'iso' => 807 ],
	['code' => 'MKN', 'display' => 'Macedonian Denar (1992–1993)', 'symbol' => 'MKN', 'digits' => 2, 'iso' => 0 ],
	['code' => 'MLF', 'display' => 'Malian Franc', 'symbol' => 'MLF', 'digits' => 2, 'iso' => 466 ],
	['code' => 'MMK', 'display' => 'Myanmar Kyat', 'symbol' => 'MMK', 'digits' => 0, 'iso' => 104 ],
	['code' => 'MNT', 'display' => 'Mongolian Tugrik', 'symbol' => 'MNT', 'digits' => 0, 'iso' => 496 ],
	['code' => 'MOP', 'display' => 'Macanese Pataca', 'symbol' => 'MOP', 'digits' => 2, 'iso' => 446 ],
	['code' => 'MRO', 'display' => 'Mauritanian Ouguiya', 'symbol' => 'MRO', 'digits' => 0, 'iso' => 478 ],
	['code' => 'MTL', 'display' => 'Maltese Lira', 'symbol' => 'MTL', 'digits' => 2, 'iso' => 470 ],
	['code' => 'MTP', 'display' => 'Maltese Pound', 'symbol' => 'MTP', 'digits' => 2, 'iso' => 470 ],
	['code' => 'MUR', 'display' => 'Mauritian Rupee', 'symbol' => 'MUR', 'digits' => 0, 'iso' => 480 ],
	['code' => 'MVR', 'display' => 'Maldivian Rufiyaa', 'symbol' => 'MVR', 'digits' => 2, 'iso' => 462 ],
	['code' => 'MWK', 'display' => 'Malawian Kwacha', 'symbol' => 'MWK', 'digits' => 2, 'iso' => 454 ],
	['code' => 'MXN', 'display' => 'Mexican Peso', 'symbol' => 'MX$', 'digits' => 2, 'iso' => 484 ],
	['code' => 'MXP', 'display' => 'Mexican Silver Peso (1861–1992)', 'symbol' => 'MXP', 'digits' => 2, 'iso' => 484 ],
	['code' => 'MXV', 'display' => 'Mexican Investment Unit', 'symbol' => 'MXV', 'digits' => 2, 'iso' => 979 ],
	['code' => 'MYR', 'display' => 'Malaysian Ringgit', 'symbol' => 'MYR', 'digits' => 2, 'iso' => 458 ],
	['code' => 'MZE', 'display' => 'Mozambican Escudo', 'symbol' => 'MZE', 'digits' => 2, 'iso' => 508 ],
	['code' => 'MZM', 'display' => 'Mozambican Metical (1980–2006)', 'symbol' => 'MZM', 'digits' => 2, 'iso' => 508 ],
	['code' => 'MZN', 'display' => 'Mozambican Metical', 'symbol' => 'MZN', 'digits' => 2, 'iso' => 943 ],
	['code' => 'NAD', 'display' => 'Namibian Dollar', 'symbol' => 'NAD', 'digits' => 2, 'iso' => 516 ],
	['code' => 'NGN', 'display' => 'Nigerian Naira', 'symbol' => 'NGN', 'digits' => 2, 'iso' => 566 ],
	['code' => 'NIC', 'display' => 'Nicaraguan Córdoba (1988–1991)', 'symbol' => 'NIC', 'digits' => 2, 'iso' => 558 ],
	['code' => 'NIO', 'display' => 'Nicaraguan Córdoba', 'symbol' => 'NIO', 'digits' => 2, 'iso' => 558 ],
	['code' => 'NLG', 'display' => 'Dutch Guilder', 'symbol' => 'NLG', 'digits' => 2, 'iso' => 528 ],
	['code' => 'NOK', 'display' => 'Norwegian Krone', 'symbol' => 'NOK', 'digits' => 2, 'iso' => 578 ],
	['code' => 'NPR', 'display' => 'Nepalese Rupee', 'symbol' => 'NPR', 'digits' => 2, 'iso' => 524 ],
	['code' => 'NZD', 'display' => 'New Zealand Dollar', 'symbol' => 'NZ$', 'digits' => 2, 'iso' => 554 ],
	['code' => 'OMR', 'display' => 'Omani Rial', 'symbol' => 'OMR', 'digits' => 3, 'iso' => 512 ],
	['code' => 'PAB', 'display' => 'Panamanian Balboa', 'symbol' => 'PAB', 'digits' => 2, 'iso' => 590 ],
	['code' => 'PEI', 'display' => 'Peruvian Inti', 'symbol' => 'PEI', 'digits' => 2, 'iso' => 604 ],
	['code' => 'PEN', 'display' => 'Peruvian Sol', 'symbol' => 'PEN', 'digits' => 2, 'iso' => 604 ],
	['code' => 'PES', 'display' => 'Peruvian Sol (1863–1965)', 'symbol' => 'PES', 'digits' => 2, 'iso' => 604 ],
	['code' => 'PGK', 'display' => 'Papua New Guinean Kina', 'symbol' => 'PGK', 'digits' => 2, 'iso' => 598 ],
	['code' => 'PHP', 'display' => 'Philippine Piso', 'symbol' => 'PHP', 'digits' => 2, 'iso' => 608 ],
	['code' => 'PKR', 'display' => 'Pakistani Rupee', 'symbol' => 'PKR', 'digits' => 0, 'iso' => 586 ],
	['code' => 'PLN', 'display' => 'Polish Zloty', 'symbol' => 'PLN', 'digits' => 2, 'iso' => 985 ],
	['code' => 'PLZ', 'display' => 'Polish Zloty (1950–1995)', 'symbol' => 'PLZ', 'digits' => 2, 'iso' => 616 ],
	['code' => 'PTE', 'display' => 'Portuguese Escudo', 'symbol' => 'PTE', 'digits' => 2, 'iso' => 620 ],
	['code' => 'PYG', 'display' => 'Paraguayan Guarani', 'symbol' => 'PYG', 'digits' => 0, 'iso' => 600 ],
	['code' => 'QAR', 'display' => 'Qatari Rial', 'symbol' => 'QAR', 'digits' => 2, 'iso' => 634 ],
	['code' => 'RHD', 'display' => 'Rhodesian Dollar', 'symbol' => 'RHD', 'digits' => 2, 'iso' => 716 ],
	['code' => 'ROL', 'display' => 'Romanian Leu (1952–2006)', 'symbol' => 'ROL', 'digits' => 2, 'iso' => 642 ],
	['code' => 'RON', 'display' => 'Romanian Leu', 'symbol' => 'RON', 'digits' => 2, 'iso' => 946 ],
	['code' => 'RSD', 'display' => 'Serbian Dinar', 'symbol' => 'RSD', 'digits' => 0, 'iso' => 941 ],
	['code' => 'RUB', 'display' => 'Russian Ruble', 'symbol' => 'RUB', 'digits' => 2, 'iso' => 643 ],
	['code' => 'RUR', 'display' => 'Russian Ruble (1991–1998)', 'symbol' => 'RUR', 'digits' => 2, 'iso' => 810 ],
	['code' => 'RWF', 'display' => 'Rwandan Franc', 'symbol' => 'RWF', 'digits' => 0, 'iso' => 646 ],
	['code' => 'SAR', 'display' => 'Saudi Riyal', 'symbol' => 'SAR', 'digits' => 2, 'iso' => 682 ],
	['code' => 'SBD', 'display' => 'Solomon Islands Dollar', 'symbol' => 'SBD', 'digits' => 2, 'iso' => 90 ],
	['code' => 'SCR', 'display' => 'Seychellois Rupee', 'symbol' => 'SCR', 'digits' => 2, 'iso' => 690 ],
	['code' => 'SDD', 'display' => 'Sudanese Dinar (1992–2007)', 'symbol' => 'SDD', 'digits' => 2, 'iso' => 736 ],
	['code' => 'SDG', 'display' => 'Sudanese Pound', 'symbol' => 'SDG', 'digits' => 2, 'iso' =>  938],
	['code' => 'SDP', 'display' => 'Sudanese Pound (1957–1998)', 'symbol' => 'SDP', 'digits' => 2, 'iso' => 736 ],
	['code' => 'SEK', 'display' => 'Swedish Krona', 'symbol' => 'SEK', 'digits' => 2, 'iso' => 752 ],
	['code' => 'SGD', 'display' => 'Singapore Dollar', 'symbol' => 'SGD', 'digits' => 2, 'iso' => 702 ],
	['code' => 'SHP', 'display' => 'St. Helena Pound', 'symbol' => 'SHP', 'digits' => 2, 'iso' => 654 ],
	['code' => 'SIT', 'display' => 'Slovenian Tolar', 'symbol' => 'SIT', 'digits' => 2, 'iso' => 705 ],
	['code' => 'SKK', 'display' => 'Slovak Koruna', 'symbol' => 'SKK', 'digits' => 2, 'iso' => 703 ],
	['code' => 'SLL', 'display' => 'Sierra Leonean Leone', 'symbol' => 'SLL', 'digits' => 0, 'iso' => 694 ],
	['code' => 'SOS', 'display' => 'Somali Shilling', 'symbol' => 'SOS', 'digits' => 0, 'iso' => 706 ],
	['code' => 'SRD', 'display' => 'Surinamese Dollar', 'symbol' => 'SRD', 'digits' => 2, 'iso' => 968 ],
	['code' => 'SRG', 'display' => 'Surinamese Guilder', 'symbol' => 'SRG', 'digits' => 2, 'iso' => 740 ],
	['code' => 'SSP', 'display' => 'South Sudanese Pound', 'symbol' => 'SSP', 'digits' => 2, 'iso' => 728 ],
	['code' => 'STD', 'display' => 'São Tomé & Príncipe Dobra', 'symbol' => 'STD', 'digits' => 0, 'iso' => 678 ],
	['code' => 'STN', 'display' => 'São Tomé & Príncipe Dobra (2018)', 'symbol' => 'STN', 'digits' => 2, 'iso' => 0 ],
	['code' => 'SUR', 'display' => 'Soviet Rouble ', 'symbol' => 'SUR', 'digits' => 2, 'iso' => 810 ],
	['code' => 'SVC', 'display' => 'Salvadoran Colón', 'symbol' => 'SVC', 'digits' => 2, 'iso' => 222 ],
	['code' => 'SYP', 'display' => 'Syrian Pound', 'symbol' => 'SYP', 'digits' => 0, 'iso' => 760 ],
	['code' => 'SZL', 'display' => 'Swazi Lilangeni', 'symbol' => 'SZL', 'digits' => 2, 'iso' => 748 ],
	['code' => 'THB', 'display' => 'Thai Baht', 'symbol' => '฿', 'digits' => 2, 'iso' => 764 ],
	['code' => 'TJR', 'display' => 'Tajikistani Ruble', 'symbol' => 'TJR', 'digits' => 2, 'iso' => 762 ],
	['code' => 'TJS', 'display' => 'Tajikistani Somoni', 'symbol' => 'TJS', 'digits' => 2, 'iso' => 972 ],
	['code' => 'TMM', 'display' => 'Turkmenistani Manat (1993–2009)', 'symbol' => 'TMM', 'digits' => 0, 'iso' => 795 ],
	['code' => 'TMT', 'display' => 'Turkmenistani Manat', 'symbol' => 'TMT', 'digits' => 2, 'iso' => 934 ],
	['code' => 'TND', 'display' => 'Tunisian Dinar', 'symbol' => 'TND', 'digits' => 3, 'iso' => 788 ],
	['code' => 'TOP', 'display' => 'Tongan Paʻanga', 'symbol' => 'TOP', 'digits' => 2, 'iso' =>  776],
	['code' => 'TPE', 'display' => 'Timorese Escudo', 'symbol' => 'TPE', 'digits' => 2, 'iso' => 626 ],
	['code' => 'TRL', 'display' => 'Turkish Lira (1922–2005)', 'symbol' => 'TRL', 'digits' => 0, 'iso' => 792 ],
	['code' => 'TRY', 'display' => 'Turkish Lira', 'symbol' => 'TRY', 'digits' => 2, 'iso' => 949 ],
	['code' => 'TTD', 'display' => 'Trinidad & Tobago Dollar', 'symbol' => 'TTD', 'digits' => 2, 'iso' => 780 ],
	['code' => 'TWD', 'display' => 'New Taiwan Dollar', 'symbol' => 'NT$', 'digits' =>2 , 'iso' => 901 ],
	['code' => 'TZS', 'display' => 'Tanzanian Shilling', 'symbol' => 'TZS', 'digits' => 0, 'iso' => 834 ],
	['code' => 'UAH', 'display' => 'Ukrainian Hryvnia', 'symbol' => 'UAH', 'digits' => 2, 'iso' => 980 ],
	['code' => 'UAK', 'display' => 'Ukrainian Karbovanets', 'symbol' => 'UAK', 'digits' => 2, 'iso' => 804 ],
	['code' => 'UGS', 'display' => 'Ugandan Shilling (1966–1987)', 'symbol' => 'UGS', 'digits' => 2, 'iso' => 800 ],
	['code' => 'UGX', 'display' => 'Ugandan Shilling', 'symbol' => 'UGX', 'digits' => 0, 'iso' => 800 ],
	['code' => 'USD', 'display' => 'US Dollar', 'symbol' => '$', 'digits' => 2, 'iso' => 840 ],
	['code' => 'USN', 'display' => 'US Dollar (Next day)', 'symbol' => 'USN', 'digits' => 2, 'iso' => 997 ],
	['code' => 'USS', 'display' => 'US Dollar (Same day)', 'symbol' => 'USS', 'digits' => 2, 'iso' => 998 ],
	['code' => 'UYI', 'display' => 'Uruguayan Peso (Indexed Units)', 'symbol' => 'UYI', 'digits' => 0, 'iso' => 940 ],
	['code' => 'UYP', 'display' => 'Uruguayan Peso (1975–1993)', 'symbol' => 'UYP', 'digits' => 2, 'iso' => 858 ],
	['code' => 'UYU', 'display' => 'Uruguayan Peso', 'symbol' => 'UYU', 'digits' => 2, 'iso' => 858 ],
	['code' => 'UZS', 'display' => 'Uzbekistani Som', 'symbol' => 'UZS', 'digits' => 0, 'iso' => 860 ],
	['code' => 'VEB', 'display' => 'Venezuelan Bolívar (1871–2008)', 'symbol' => 'VEB', 'digits' => 2, 'iso' => 862 ],
	['code' => 'VEF', 'display' => 'Venezuelan Bolívar', 'symbol' => 'VEF', 'digits' => 2, 'iso' => 937 ],
	['code' => 'VND', 'display' => 'Vietnamese Dong', 'symbol' => '₫', 'digits' => 0, 'iso' => 704 ],
	['code' => 'VNN', 'display' => 'Vietnamese Dong (1978–1985)', 'symbol' => 'VNN', 'digits' => 2, 'iso' => 0 ],
	['code' => 'VUV', 'display' => 'Vanuatu Vatu', 'symbol' => 'VUV', 'digits' => 0, 'iso' => 548 ],
	['code' => 'WST', 'display' => 'Samoan Tala', 'symbol' => 'WST', 'digits' => 2, 'iso' => 882 ],
	['code' => 'XAF', 'display' => 'Central African CFA Franc', 'symbol' => 'FCFA', 'digits' => 0, 'iso' => 950 ],
	['code' => 'XAG', 'display' => 'Silver', 'symbol' => 'XAG', 'digits' => 2, 'iso' => 961 ],
	['code' => 'XAU', 'display' => 'Gold', 'symbol' => 'XAU', 'digits' => 2, 'iso' => 959 ],
	['code' => 'XBA', 'display' => 'European Composite Unit', 'symbol' => 'XBA', 'digits' => 2, 'iso' => 955 ],
	['code' => 'XBB', 'display' => 'European Monetary Unit', 'symbol' => 'XBB', 'digits' => 2, 'iso' => 956 ],
	['code' => 'XBC', 'display' => 'European Unit of Account (XBC)', 'symbol' => 'XBC', 'digits' => 2, 'iso' => 957 ],
	['code' => 'XBD', 'display' => 'European Unit of Account (XBD)', 'symbol' => 'XBD', 'digits' => 2, 'iso' => 958 ],
	['code' => 'XCD', 'display' => 'East Caribbean Dollar', 'symbol' => 'EC$', 'digits' => 2, 'iso' => 951 ],
	['code' => 'XDR', 'display' => 'Special Drawing Rights', 'symbol' => 'XDR', 'digits' => 2, 'iso' => 960 ],
	['code' => 'XEU', 'display' => 'European Currency Unit', 'symbol' => 'XEU', 'digits' => 2, 'iso' => 954 ],
	['code' => 'XFO', 'display' => 'French Gold Franc', 'symbol' => 'XFO', 'digits' => 2, 'iso' => 0 ],
	['code' => 'XFU', 'display' => 'French UIC-Franc', 'symbol' => 'XFU', 'digits' => 2, 'iso' => 0 ],
	['code' => 'XOF', 'display' => 'West African CFA Franc', 'symbol' => 'CFA', 'digits' => 0, 'iso' => 952 ],
	['code' => 'XPD', 'display' => 'Palladium', 'symbol' => 'XPD', 'digits' => 2, 'iso' => 964 ],
	['code' => 'XPF', 'display' => 'CFP Franc', 'symbol' => 'CFPF', 'digits' => 0, 'iso' => 953 ],
	['code' => 'XPT', 'display' => 'Platinum', 'symbol' => 'XPT', 'digits' => 2, 'iso' => 962 ],
	['code' => 'XRE', 'display' => 'RINET Funds', 'symbol' => 'XRE', 'digits' => 2, 'iso' => 0 ],
	['code' => 'XSU', 'display' => 'Sucre', 'symbol' => 'XSU', 'digits' => 2, 'iso' => 994 ],
	['code' => 'XTS', 'display' => 'Testing Currency Code', 'symbol' => 'XTS', 'digits' => 2, 'iso' => 963 ],
	['code' => 'XUA', 'display' => 'ADB Unit of Account', 'symbol' => 'XUA', 'digits' => 2, 'iso' => 965 ],
	['code' => 'XXX', 'display' => 'Unknown Currency', 'symbol' => 'XXX', 'digits' => 2, 'iso' => 999 ],
	['code' => 'YDD', 'display' => 'Yemeni Dinar', 'symbol' => 'YDD', 'digits' => 2, 'iso' => 720 ],
	['code' => 'YER', 'display' => 'Yemeni Rial', 'symbol' => 'YER', 'digits' => 0, 'iso' => 886 ],
	['code' => 'YUD', 'display' => 'Yugoslavian Hard Dinar (1966–1990)', 'symbol' => 'YUD', 'digits' => 2, 'iso' => 891 ],
	['code' => 'YUM', 'display' => 'Yugoslavian New Dinar (1994–2002)', 'symbol' => 'YUM', 'digits' => 2, 'iso' => 891 ],
	['code' => 'YUN', 'display' => 'Yugoslavian Convertible Dinar (1990–1992)', 'symbol' => 'YUN', 'digits' => 2, 'iso' => 890 ],
	['code' => 'YUR', 'display' => 'Yugoslavian Reformed Dinar (1992–1993)', 'symbol' => 'YUR', 'digits' => 2, 'iso' => 0 ],
	['code' => 'ZAL', 'display' => 'South African Rand (financial)', 'symbol' => 'ZAL', 'digits' => 2, 'iso' => 991 ],
	['code' => 'ZAR', 'display' => 'South African Rand', 'symbol' => 'ZAR', 'digits' => 2, 'iso' => 710 ],
	['code' => 'ZMK', 'display' => 'Zambian Kwacha (1968–2012)', 'symbol' => 'ZMK', 'digits' => 0, 'iso' => 894 ],
	['code' => 'ZMW', 'display' => 'Zambian Kwacha', 'symbol' => 'ZMW', 'digits' => 2, 'iso' => 967 ],
	['code' => 'ZRN', 'display' => 'Zairean New Zaire (1993–1998)', 'symbol' => 'ZRN', 'digits' => 2, 'iso' => 180 ],
	['code' => 'ZRZ', 'display' => 'Zairean Zaire (1971–1993)', 'symbol' => 'ZRZ', 'digits' => 2, 'iso' => 180 ],
	['code' => 'ZWD', 'display' => 'Zimbabwean Dollar (1980–2008)', 'symbol' => 'ZWD', 'digits' => 0, 'iso' => 716 ],
	['code' => 'ZWL', 'display' => 'Zimbabwean Dollar (2009)', 'symbol' => 'ZWL', 'digits' => 2, 'iso' => 932 ],
	['code' => 'ZWR', 'display' => 'Zimbabwean Dollar (2008)', 'symbol' => 'ZWR', 'digits' => 2, 'iso' => 935 ],

];